"""The gallery: the text of `build/README.md`, a table of every symbol with its two renderings."""

from urllib.parse import quote

import deal

from symdef.model import Library, Symbol

_INTRO = (
    "Generated by `write_build`; do not edit. A symbol stays `unverified` until its geometry"
    " is compared with the standard's own drawing."
)
_HEADER = ("Number", "Name", "Kind", "Status", "Plain", "Annotated")
_TAG = "-X1"
_VALUE = "10 A"


@deal.pure
def sample_texts(symbol: Symbol) -> dict[str, str]:
    """Return the sample text the annotated SVG shows in each slot (D33).

    `tag` is `-X1`, `value` is `10 A`, and `marking.<port id>` is the 1-based position of the port
    in `symbol.ports` (the first one, for ports that share an id). Keys are given for slots the
    symbol may not have; `to_svg` ignores those.
    """
    texts = {"tag": _TAG, "value": _VALUE}
    for index, port in enumerate(symbol.ports, start=1):
        texts.setdefault(f"marking.{port.id}", str(index))
    return texts


@deal.pure
def _line(text: str) -> str:
    """Put text on one line: every run of whitespace, line breaks included, becomes one space."""
    return " ".join(text.split())


@deal.pure
def _cell(text: str) -> str:
    """Make text safe inside a Markdown table cell."""
    return _line(text).replace("|", "\\|")


@deal.pure
def _row(number: str, library: Library) -> str:
    """Return the table row of one symbol: its facts, then the plain and annotated images."""
    symbol = library.symbols[number]
    label = _cell(number)
    link = quote(number, safe="", errors="replace")
    cells = (
        f"[{label}](resolved/{link}.json)",
        _cell(symbol.name),
        symbol.kind.value,
        symbol.status.value,
        f"![{label}](svg/{link}.svg)",
        f"![{label} annotated](annotated/{link}.svg)",
    )
    return "| " + " | ".join(cells) + " |"


@deal.pure
def readme(library: Library) -> str:
    """Return the README of a build.

    A heading, one line on the status, and a table of the symbols sorted by number with their
    kind, their status and their plain and annotated SVG side by side. Links are relative to
    `build/`. Only the standard is used, never the title, so a library loaded from a bundle gives
    the same text as the one loaded from the sources.

    Args:
        library: The library the build is made from.

    Returns:
        The Markdown text with LF line endings and one trailing newline.
    """
    lines = [
        f"# {_line(library.standard)} symbols",
        "",
        _INTRO,
        "",
        "| " + " | ".join(_HEADER) + " |",
        "| " + " | ".join("---" for _ in _HEADER) + " |",
        *(_row(number, library) for number in sorted(library.symbols)),
    ]
    return "\n".join(lines) + "\n"
