"""The gallery README text."""

from dataclasses import replace
from pathlib import Path

from graphical_symbols.build import load_library
from graphical_symbols.gallery import readme
from graphical_symbols.model import Library, Status, SymbolKind

GUIDE = Path(__file__).resolve().parent / "fixtures" / "guide"
LIBRARY = load_library(GUIDE)


def one_symbol_library(**changes) -> Library:
    symbol = replace(LIBRARY.get("S00227"), **changes)
    return Library("IEC 60617", "a title", r"^S\d{5}$", {"S00227": symbol})


def test_the_text_of_a_one_symbol_gallery_is_exact():
    assert readme(one_symbol_library()) == (
        "# IEC 60617 symbols\n"
        "\n"
        "Generated by `write_build`; do not edit. A symbol stays `unverified` until its geometry"
        " is compared with the standard's own drawing.\n"
        "\n"
        "| Number | Name | Kind | Status | Plain | Annotated |\n"
        "| --- | --- | --- | --- | --- | --- |\n"
        "| [S00227](resolved/S00227.json) | Make contact, general symbol | symbol | unverified"
        " | ![S00227](svg/S00227.svg) | ![S00227 annotated](annotated/S00227.svg) |\n"
    )


def test_rows_are_sorted_by_number_whatever_the_order_of_the_library():
    symbols = {n: LIBRARY.get(n) for n in ("S00305", "S00016", "S00254")}
    rows = readme(Library("X", "t", "", symbols)).splitlines()[6:]
    assert [row.split("]")[0] for row in rows] == ["| [S00016", "| [S00254", "| [S00305"]


def test_the_status_of_every_symbol_is_shown_next_to_it():
    verified = one_symbol_library(status=Status.VERIFIED)
    assert "| symbol | verified |" in readme(verified)
    assert "| symbol | unverified |" in readme(one_symbol_library())


def test_the_kind_is_shown():
    assert "| qualifier |" in readme(one_symbol_library(kind=SymbolKind.QUALIFIER))


def test_plain_and_annotated_images_sit_in_the_same_row_with_relative_links():
    (row,) = readme(one_symbol_library()).splitlines()[6:]
    assert row.index("![S00227](svg/S00227.svg)") < row.index(
        "![S00227 annotated](annotated/S00227.svg)"
    )


def test_the_gallery_uses_the_standard_and_never_the_title():
    text = readme(one_symbol_library())
    assert text.startswith("# IEC 60617 symbols\n")
    assert "a title" not in text


def test_a_name_cannot_break_the_table():
    text = readme(one_symbol_library(name="a | b\r\nc"))
    (row,) = text.splitlines()[6:]
    assert "a \\| b c" in row
    assert "\r" not in text


def test_a_lone_surrogate_in_a_number_does_not_raise():
    symbol = LIBRARY.get("S00227")
    (row,) = readme(Library("X", "t", "", {"S\ud800": symbol})).splitlines()[6:]
    assert "resolved/S%3F.json" in row


def test_a_library_without_symbols_has_the_header_only():
    lines = readme(Library("X", "t", "", {})).splitlines()
    assert lines[4:] == [
        "| Number | Name | Kind | Status | Plain | Annotated |",
        "| --- | --- | --- | --- | --- | --- |",
    ]


def test_the_text_is_deterministic_with_lf_and_one_trailing_newline():
    text = readme(LIBRARY)
    assert text == readme(load_library(GUIDE))
    assert "\r" not in text
    assert text.endswith("|\n")
    assert not text.endswith("\n\n")
