"""The gallery: the text of `build/README.md`, a table of every symbol with its two renderings."""

from urllib.parse import quote

import deal

from graphical_symbols.model import Library

_INTRO = (
    "Generated by `write_build`; do not edit. A symbol stays `unverified` until its geometry"
    " is compared with the standard's own drawing."
)
_HEADER = ("Number", "Name", "Kind", "Status", "Plain", "Annotated")


@deal.pure
def _line(text: str) -> str:
    """Put text on one line: every run of whitespace, line breaks included, becomes one space."""
    return " ".join(text.split())


@deal.pure
def _cell(text: str) -> str:
    """Make text safe inside a Markdown table cell."""
    return _line(text).replace("|", "\\|")


@deal.pure
def _row(number: str, library: Library) -> str:
    """Return the table row of one symbol: its facts, then the plain and annotated images."""
    symbol = library.symbols[number]
    label = _cell(number)
    link = quote(number, safe="")
    cells = (
        f"[{label}](resolved/{link}.json)",
        _cell(symbol.name),
        symbol.kind.value,
        symbol.status.value,
        f"![{label}](svg/{link}.svg)",
        f"![{label} annotated](annotated/{link}.svg)",
    )
    return "| " + " | ".join(cells) + " |"


@deal.pure
def readme(library: Library) -> str:
    """Return the README of a build.

    A heading, one line on the status, and a table of the symbols sorted by number with their
    kind, their status and their plain and annotated SVG side by side. Links are relative to
    `build/`. Only the standard is used, never the title, so a library loaded from a bundle gives
    the same text as the one loaded from the sources.

    Args:
        library: The library the build is made from.

    Returns:
        The Markdown text with LF line endings and one trailing newline.
    """
    lines = [
        f"# {_line(library.standard)} symbols",
        "",
        _INTRO,
        "",
        "| " + " | ".join(_HEADER) + " |",
        "| " + " | ".join("---" for _ in _HEADER) + " |",
        *(_row(number, library) for number in sorted(library.symbols)),
    ]
    return "\n".join(lines) + "\n"
